### ISSUE TITLE
Error when trying to scan EAN-8 products

### ISSUE THREAD

**Issue by Derthorn** [skanna-app/issues#2]
### Problem Statement

I get an error when trying to scan an ketchup bottle utilizes an EAN-8 barcode.
![ean-8_ketchup](https://user-images.githubusercontent.com/5654609/192353185-a1999b0b-7e1d-40d0-9cea-4556f1c1042b.jpg)

### Proposed Solution

EAN-8 barcodes are accepted and able to be scanned.

### Alternatives

Not being able to scan my entire fridge.

**Comment by Swiftwork** [comment]
Service now supports this with https://github.com/skanna-app/service/commit/dae46f651bd132f17becac8998b57ce678622b23. Work to be done on the client.

**Comment by Swiftwork** [comment]
The internal distribution build 1.1.0-rc.4 has resolved this issue. 🎉
